"""initial schema

Revision ID: 62e3b3c86ab0
Revises: 
Create Date: 2026-10-06 02:46:31.425663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '62e3b3c86ab0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invite_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pool_balance', sa.Integer(), nullable=False),
    sa.Column('worker_pct', sa.Integer(), nullable=False),
    sa.Column('referrer_pct', sa.Integer(), nullable=False),
    sa.Column('pool_pct', sa.Integer(), nullable=False),
    sa.Column('monthly_fee', sa.Integer(), nullable=False),
    sa.Column('claim_wait_days', sa.Integer(), nullable=False),
    sa.Column('claim_cap_pct', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guilds_invite_code'), 'guilds', ['invite_code'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paypal_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_paypal_event_id'), 'webhook_events', ['paypal_event_id'], unique=True)
    op.create_table('agent_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guild_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_actions_guild_id'), 'agent_actions', ['guild_id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guild_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paypal_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('hourly_rate_cents', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_guild_id'), 'members', ['guild_id'], unique=False)
    op.create_index(op.f('ix_members_user_id'), 'members', ['user_id'], unique=True)
    op.create_table('pool_tx',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guild_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_tx_guild_id'), 'pool_tx', ['guild_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guild_id', sa.Uuid(), nullable=False),
    sa.Column('referrer_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_guild_id'), 'jobs', ['guild_id'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guild_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paypal_batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_guild_id'), 'payouts', ['guild_id'], unique=False)
    op.create_index(op.f('ix_payouts_member_id'), 'payouts', ['member_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guild_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('paypal_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_guild_id'), 'subscriptions', ['guild_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_member_id'), 'subscriptions', ['member_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_paypal_subscription_id'), 'subscriptions', ['paypal_subscription_id'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_job_id'), 'milestones', ['job_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('milestone_id', sa.Uuid(), nullable=False),
    sa.Column('paypal_invoice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_milestone_id'), 'invoices', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_invoices_paypal_invoice_id'), 'invoices', ['paypal_invoice_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guild_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_urls', sa.JSON(), nullable=True),
    sa.Column('ai_verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('admin_decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payout_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_guild_id'), 'claims', ['guild_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_guild_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_invoices_paypal_invoice_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_milestone_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_milestones_job_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_subscriptions_paypal_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_member_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_guild_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_payouts_member_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_guild_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_jobs_guild_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_pool_tx_guild_id'), table_name='pool_tx')
    op.drop_table('pool_tx')
    op.drop_index(op.f('ix_members_user_id'), table_name='members')
    op.drop_index(op.f('ix_members_guild_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_agent_actions_guild_id'), table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index(op.f('ix_webhook_events_paypal_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_guilds_invite_code'), table_name='guilds')
    op.drop_table('guilds')
    # ### end Alembic commands ###
