"""reminders

Revision ID: fe9697e2cabd
Revises: 094ebf9d5767
Create Date: 2026-10-07 03:10:12.327190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe9697e2cabd'
down_revision: Union[str, Sequence[str], None] = '094ebf9d5767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guild_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('written_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'tier', name='uq_reminder_invoice_tier')
    )
    op.create_index(op.f('ix_reminders_guild_id'), 'reminders', ['guild_id'], unique=False)
    op.create_index(op.f('ix_reminders_invoice_id'), 'reminders', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_invoice_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_guild_id'), table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
